[package]
name = "substrate-metadata"
version = "0.1.0"
authors = ["Bryan Chen <xlchen1291@gmail.com>"]

[dependencies]
parity-codec = { version = "2.1", default-features = false }
parity-codec-derive = { version = "2.1", default-features = false }
serde = { version = "1.0", default-features = false }
serde_derive = { version = "1.0", optional = true }

[features]
default = ["std"]
std = [
	"serde/std",
	"serde_derive",
]
