[package]
name = "sp-historical-data"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Data associated with its history"
edition = "2018"

[dependencies]
smallvec = { version = "0.6", default-features = false }

[features]
default = ["std"]
std = [
  "smallvec/std",
]
test-helpers = []
