
[package]
name = "substrate-state-machine-fuzz"
version = "0.0.1"
authors = []
publish = false
edition = "2018"

[package.metadata]
cargo-fuzz = true

[dependencies.substrate-state-machine]
path = ".."
features = ["test"]

[dependencies.libfuzzer-sys]
git = "https://github.com/rust-fuzz/libfuzzer-sys.git"

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[[bin]]
name = "fuzz_transactions_no_gc"
path = "fuzz_targets/fuzz_transactions.rs"

[[bin]]
name = "fuzz_transactions_with_gc"
path = "fuzz_targets/fuzz_transactions_with_gc.rs"
