[package]
name = "sp-externalities"
version = "0.8.0-rc5"
license = "Apache-2.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "Substrate externalities abstraction"
documentation = "https://docs.rs/sp-externalities"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-storage = { version = "2.0.0-rc5", path = "../storage", default-features = false }
sp-std = { version = "2.0.0-rc5", path = "../std", default-features = false }
environmental = { version = "1.1.1", optional = true }
codec = { package = "parity-scale-codec", version = "1.3.1", default-features = false }

[features]
default = ["std"]
std = [
	"codec/std",
  "sp-std/std",
  "sp-storage/std",

	"environmental",
]
