[package]
name = "sp-tasks"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "Runtime asynchronous, pure computational tasks"
documentation = "https://docs.rs/sp-tasks"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
log = { version = "0.4.8", optional = true }
sp-core = { version = "2.0.0", default-features = false, path = "../core" }
sp-externalities = { version = "0.8.0", default-features = false, path = "../externalities" }
sp-io = { version = "2.0.0", default-features = false, path = "../io" }
sp-runtime-interface = { version = "2.0.0", default-features = false, path = "../runtime-interface" }
sp-state-machine = { version = "0.8.0", default-features = false, path = "../state-machine" }
sp-std = { version = "2.0.0", default-features = false, path = "../std" }
sp-panic-handler = { version = "2.0.0", optional = true, path = "../panic-handler" }
sp-wasm-interface = { version = "2.0.0", default-features = false, path = "../wasm-interface" }
parking_lot = { version = "0.10.2", optional = true }

[dev-dependencies]
codec = { package = "parity-scale-codec", default-features = false, version = "1.3.1" }

[features]
default = ["std"]
std = [
	"log",
	"sp-core/std",
	"sp-externalities/std",
	"sp-panic-handler",
	"sp-io/std",
	"sp-runtime-interface/std",
	"sp-state-machine/std",
	"sp-std/std",
	"sp-wasm-interface/std",
	"parking_lot",
]
