[package]
name = "sp-tasks"
version = "3.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "Runtime asynchronous, pure computational tasks"
documentation = "https://docs.rs/sp-tasks"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
derive_more = { version = "0.99.2", optional = true }
log = { version = "0.4.8", optional = true }
parking_lot = { version = "0.11.1", optional = true }
thiserror = { version = "1.0.21", optional = true }
ambassador = "0.2.1"
sp-core = { version = "3.0.0", default-features = false, path = "../core" }
sp-externalities = { version = "0.9.0", default-features = false, path = "../externalities" }
sp-io = { version = "3.0.0", default-features = false, path = "../io" }
sp-std = { version = "3.0.0", default-features = false, path = "../std" }
wasmi = { version = "0.6.2", optional = true }
sp-panic-handler = { version = "3.0.0", optional = true, path = "../panic-handler" }
sp-allocator = { version = "3.0.0", optional = true, path = "../allocator" }
sp-wasm-interface = { version = "3.0.0", default-features = false, path = "../wasm-interface" }
sp-runtime-interface = { version = "3.0.0", default-features = false, path = "../runtime-interface" }
sp-serializer = { version = "3.0.0", optional = true, path = "../serializer" }

[dev-dependencies]
codec = { package = "parity-scale-codec", default-features = false, version = "2.0.0" }

[features]
default = ["std", "abort-future"]
# Do try to abort future.
# This is behind a feature for not being very useful.
abort-future = []
std = [
	"derive_more",
	"log",
	"parking_lot",
  "sp-allocator",
  "sp-serializer",
  "thiserror",
  "wasmi",
	"sp-core/std",
	"sp-externalities/std",
	"sp-panic-handler",
	"sp-io/std",
	"sp-std/std",
	"sp-wasm-interface/std",
]
