[package]
name = "substrate-test-runtime-wasm"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[lib]
name = "substrate_test_runtime"
crate-type = ["cdylib"]

[dependencies]
substrate-test-runtime = { path = "..", default-features = false }

[features]
default = []
std = [
	"substrate-test-runtime/std",
]

[profile.release]
panic = "abort"
lto = true

[workspace]
members = []

[patch.crates-io]
trie-db = { git = "https://github.com/cheme/trie.git", branch = "simple-codec" }
trie-root = { git = "https://github.com/cheme/trie.git", branch = "simple-codec" }
hash-db = { git = "https://github.com/cheme/trie.git", branch = "simple-codec" }
memory-db = { git = "https://github.com/cheme/trie.git", branch = "simple-codec" }
keccak-hasher = { git = "https://github.com/cheme/trie.git", branch = "simple-codec" }

#[patch.crates-io]
#trie-db = { path = "../../../../parity-trie/trie-db" }
#trie-root = { path = "../../../../parity-trie/trie-root" }
#hash-db = { path = "../../../../parity-trie/hash-db" }
#memory-db = { path = "../../../../parity-trie/memory-db" }
#keccak-hasher = { path = "../../../../parity-trie/test-support/keccak-hasher" }
