[package]
name = "node-template-runtime-wasm"
version = "2.0.0"
authors = ["Anonymous"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
node-template-runtime = { path = "..", default-features = false }

[features]
default = []
std = [
	"node-template-runtime/std",
]

[profile.release]
panic = "abort"
lto = true

[workspace]
members = []


[patch.crates-io]
trie-db = { git = "https://github.com/cheme/trie.git", branch = "n_ext_trie" }
trie-root = { git = "https://github.com/cheme/trie.git", branch = "n_ext_trie" }
hash-db = { git = "https://github.com/cheme/trie.git", branch = "n_ext_trie" }
memory-db = { git = "https://github.com/cheme/trie.git", branch = "n_ext_trie" }
keccak-hasher = { git = "https://github.com/cheme/trie.git", branch = "n_ext_trie" }
trie-bench = { git = "https://github.com/cheme/trie.git", branch = "n_ext_trie" }

#[patch.crates-io]
#trie-db = { path = "../../../../parity-trie/trie-db" }
#trie-root = { path = "../../../../parity-trie/trie-root" }
#hash-db = { path = "../../../../parity-trie/hash-db" }
#memory-db = { path = "../../../../parity-trie/memory-db" }
#keccak-hasher = { path = "../../../../parity-trie/test-support/keccak-hasher" }
#trie-bench = { path = "../../../../parity-trie/test-support/trie-bench" }
