[package]
name = "node-template-runtime-wasm"
version = "0.9.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
node-template-runtime = { path = "..", default-features = false }

[features]
default = []
std = [
	"node-template-runtime/std",
]

[profile.release]
panic = "abort"
lto = true

[workspace]
members = []

[patch.crates-io]
trie-db = { path = "../../../../parity-trie/trie-db" }
trie-root = { path = "../../../../parity-trie/trie-root" }
hash-db = { path = "../../../../parity-trie/hash-db" }
memory-db = { path = "../../../../parity-trie/memory-db" }
trie-bench = { path = "../../../../parity-trie/test-support/trie-bench" }
hash256-std-hasher = { path = "../../../../parity-trie/hash256-std-hasher" }
