[package]
name = "sp-database"
version = "3.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "Substrate database trait."
documentation = "https://docs.rs/sp-database"
readme = "README.md"

[dependencies]
parking_lot = "0.11.1"
kvdb = "0.9.0"
parity-util-mem = { version = "0.9.0", default-features = false, features = [] }
radix-tree = { version = "0.8.0", git = "https://github.com/cheme/substrate.git", branch = "historied-db", features = ["std"] }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
sp-runtime = { version = "3.0.0", path = "../runtime" }
