[package]
name = "sp-storage"
version = "2.0.0-alpha.5"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
description = "Storage related primitives"
license = "GPL-3.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
documentation = "https://docs.rs/sp-storage/"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false, features = ["derive"] }
sp-std = { version = "2.0.0-alpha.5", default-features = false, path = "../std" }
serde = { version = "1.0.101", optional = true, features = ["derive"] }
impl-serde = { version = "0.2.3", optional = true }
sp-debug-derive = { version = "2.0.0-alpha.5", path = "../debug-derive" }
ref-cast = "1.0.0"

[features]
default = [ "std" ]
std = [ "sp-std/std", "serde", "impl-serde", "codec/std" ]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
