[package]
name = "radix-tree"
version = "0.8.0-rc3"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Radix tree traits and implementations."
license = "Apache-2.0"
categories = [ "no-std" ]
edition = "2018"


[dependencies]
derivative = { version = "2.1", features = ["use_core"] }
#smallvec = "1.0.0"
hashbrown = { version = "0.8.0", default-features = false, features = [ "ahash" ] }
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false, features = ["derive"] }
parking_lot = { version = "0.10.0", optional = true }

[dev-dependencies]
#criterion = "0.2.8"


[features]
default = []
std = ["parking_lot"]
fuzzer = []
