[package]
name = "sc-executor-common"
version = "0.8.1"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "A set of common definitions that are needed for defining execution engines."
documentation = "https://docs.rs/sc-executor-common/"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
log = { version = "0.4", optional = true }
derive_more = { version = "0.99.2", optional = true }
parity-wasm = { version = "0.41.0", optional = true }
codec = { package = "parity-scale-codec", optional = true, version = "1.3.6" }
wasmi = { version = "0.6.2", optional = true }
sp-core = { version = "2.0.0", default-features = false, path = "../../../primitives/core" }
sp-allocator = { version = "2.0.0", optional = true, path = "../../../primitives/allocator" }
sp-wasm-interface = { version = "2.0.0", optional = true, path = "../../../primitives/wasm-interface" }
sp-serializer = { version = "2.0.0", optional = true, path = "../../../primitives/serializer" }
sp-tasks = { version = "2.0.0", default-features = false, path = "../../../primitives/tasks" }
sp-externalities = { version = "0.8.0", default-features = false, path = "../../../primitives/externalities" }
sp-panic-handler = { version = "2.0.0", optional = true, path = "../../../primitives/panic-handler" }
sp-std = { version = "2.0.0", default-features = false, path = "../../../primitives/std" }
parking_lot = { version = "0.10.0", optional = true }
thiserror = { version = "1.0.21", optional = true }

[features]
default = [ "std" ]
std = [
  "log",
  "thiserror",
	"derive_more",
	"parity-wasm",
  "codec",
  "wasmi",
  "sp-allocator",
  "sp-panic-handler",
  "sp-wasm-interface",
  "sp-serializer",
  "parking_lot",
  "sp-core/std",
  "sp-externalities/std",
  "sp-std/std",
  "sp-tasks/std",
]
